name: 'Brightspot Build'
description: 'Build Brightspot'

inputs:
  project-aws-account-id:
    description: 'AWS Account ID of project'
    required: true

  cloud-aws-account-id:
    description: 'AWS Account ID of Cloud project'
    required: true

  region:
    description: 'Region project is deployed to'
    required: true
  
  project:
    description: 'Shortname for project'
    required: true

  repository:
    description: 'Repository name. This overrides the default which is ${project}/${project}'
    required: false

  aws-access-key-id: 
    description: 'AWS Access Key ID'
    required: true

  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true

  aws-session-token:
    description: 'AWS Session Token'
    required: true

  deploy-s3:
    description: 'Deploy to S3 in addition to the container build'
    required: false
    default: false

  deploy-bucket:
    description: 'S3 bucket to deploy to'
    required: false

  deploy-container:
    description: 'Deploy to container build'
    required: false
    default: true

outputs:
  container-build-tag:
    description: "Container build tag. This tag is stable and won't change."
    value: ${{ steps.build-container.outputs.container-build-tag }}

  container-version-tag:
    description: "Container version tag. This tag is unstable and may move with each build."
    value: ${{ steps.build-container.outputs.container-build-tag }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Get Tag Version
      shell: bash
      run: echo "GITHUB_ACTIONS_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Clone Github Actions S3 Deploy
      shell: bash
      run: git clone https://github.com/perfectsense/github-actions-s3-deploy.git

    - name: Build with Gradle
      shell: bash
      run: ./github-actions-s3-deploy/build-gradle.sh

    - name: Deploy to S3
      if: ${{ inputs.deploy-s3 == 'true' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_SESSION_TOKEN: ${{ inputs.aws-session-token }}
        DEPLOY_BUCKET: ${{ inputs.deploy-bucket }}
      shell: bash
      run: ./github-actions-s3-deploy/deploy.sh

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        aws-region: ${{ inputs.region }}

    - name: Login to project ECR
      uses: docker/login-action@v1
      if: ${{ inputs.deploy-container == 'true' }}
      with:
          registry: ${{ inputs.project-aws-account-id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com

    - name: Login to Brightspot Cloud ECR
      uses: docker/login-action@v1
      if: ${{ inputs.deploy-container == 'true' }}
      with:
          registry: ${{ inputs.cloud-aws-account-id }}.dkr.ecr.${{ inputs.region }}.amazonaws.com

    - name: Build Container
      id: build-container
      if: ${{ inputs.deploy-container == 'true' }}
      env:
        GITHUB_ACTIONS_PULL_REQUEST: ${{ github.event.pull_request.number }}
      shell: bash
      run: |
        version=""
        build=""

        echo "GITHUB_ACTIONS_TAG ${GITHUB_ACTIONS_TAG}"
        echo "GITHUB_ACTIONS_PULL_REQUEST ${GITHUB_ACTIONS_PULL_REQUEST}"

        if [[ ! -z "$GITHUB_ACTIONS_PULL_REQUEST" && "$GITHUB_ACTIONS_PULL_REQUEST" != "" ]]; then
            version="pullrequest-$GITHUB_ACTIONS_PULL_REQUEST"
            build=pullrequest-$GITHUB_ACTIONS_PULL_REQUEST-build$GITHUB_RUN_NUMBER
        elif [[ "$GITHUB_ACTIONS_TAG" =~ ^v[0-9]+\. ]]; then
            echo "GITHUB_ACTIONS_TAG ${GITHUB_ACTIONS_TAG}"
            version=release-${GITHUB_ACTIONS_TAG/v/}
            build=release-${GITHUB_ACTIONS_TAG/v/}
        else
            COMMIT_COUNT=$(git rev-list --count HEAD)
            COMMIT_SHA=$(git rev-parse --short=6 HEAD)
            build=development-$(git describe --all | sed 's/heads\///' | sed 's/\//-/g')
            build+=-build$GITHUB_RUN_NUMBER
            version=development-$(git describe --all | sed 's/heads\///' | sed 's/\//-/g')
        fi

        cp web/build/libs/*.war etc/container/web.war
        cd etc/container

        PROJECT="${{ inputs.project }}"
        REPOSITORY="${{ inputs.repository }}"

        if [ -z ${REPOSITORY+x} ]; then
           REPOSITORY="$PROJECT/$PROJECT"
        fi

        BUILD_TAG="${{ inputs.registry }}/$REPOSITORY:$build"
        VERSION_TAG="${{ inputs.registry }}/$REPOSITORY:$version"

        docker buildx build --push --build-arg WAR_ARTIFACT=web.war -t $VERSION_TAG -t $BUILD_TAG -f Dockerfile .

        echo "::set-output name=container-build-tag::$(echo $BUILD_TAG)"
        echo "::set-output name=container-version-tag::$(echo $VERSION_TAG)"

